### ISSUE TITLE
Zatermelon 的问题补充 WF_Sale.json 出问题的东西

### ISSUE THREAD

**Issue by Cyl18** [Richasy/WFA_Lexicon#13]
我把所有的的 WF_Sale.json 里面的东西都请求了一次 下面是 WM404 的东西: 

|ID|英文名|中文名| Search |
|:-: |:-:|:-:|:-:|
| 394 | Bronco Prime | 野马 PRIME | bronco_prime |
| 400 | Lex Prime | 雷克斯 PRIME | lex_prime |
| 449 | Dual Decurion Barrel | 什长双枪 枪管 | dual_decurion_barrel |
| 450 | Dual Decurion Receiver | 什长双枪 枪机 | dual_decurion_receiver |
| 623 | Shield Transference | 护盾转移 | shield_transference |
| 634 | Divebomb Vortex | 涡卷俯冲 | divebomb_vortex |
| 763 | Guided Ordinance | 制导弹药 | guided_ordinance |
| 957 | Blocking | 格挡 | blocking |
| 1850 | Axi Q2 Intact | 后纪 Q2 完整 | axi_q2_intact |
| 1851 | Axi Q2 Exceptional | 后纪 Q2 优良 | axi_q2_exceptional |
| 1852 | Axi Q2 Flawless | 后纪 Q2 无暇 | axi_q2_flawless |
| 1853 | Axi Q2 Radiant | 后纪 Q2 光辉 | axi_q2_radiant |
| 1858 | Axi H3 Intact | 后纪 H3 完整 | axi_H3_intact |
| 1859 | Axi H3 Exceptional | 后纪 H3 优良 | axi_H3_exceptional |
| 1860 | Axi H3 Flawless | 后纪 H3 无暇 | axi_H3_flawless |
| 1861 | Axi H3 Radiant | 后纪 H3 光辉 | axi_H3_radiant |
| 1862 | Neo B4 Intact | 中纪 B4 完整 | neo_B4_intact |
| 1863 | Neo B4 Exceptional | 中纪 B4 优良 | neo_B4_exceptional |
| 1864 | Neo B4 Flawless | 中纪 B4 无暇 | neo_B4_flawless |
| 1865 | Neo B4 Radiant | 中纪 B4 光辉 | neo_B4_radiant |
| 1866 | Neo K1 Intact | 中纪 K1 完整 | neo_K1_intact |
| 1867 | Neo K1 Exceptional | 中纪 K1 优良 | neo_K1_exceptional |
| 1868 | Neo K1 Flawless | 中纪 K1 无暇 | neo_K1_flawless |
| 1869 | Neo K1 Radiant | 中纪 K1 光辉 | neo_K1_radiant |
| 1870 | Neo Z1 Intact | 中纪 Z1 完整 | neo_Z1_intact |
| 1871 | Neo Z1 Exceptional | 中纪 Z1 优良 | neo_Z1_exceptional |
| 1872 | Neo Z1 Flawless | 中纪 Z1 无暇 | neo_Z1_flawless |
| 1873 | Neo Z1 Radiant | 中纪 Z1 光辉 | neo_Z1_radiant |
| 1874 | Meso O2 Intact | 前纪 O2 完整 | meso_O2_intact |
| 1875 | Meso O2 Exceptional | 前纪 O2 优良 | meso_O2_exceptional |
| 1876 | Meso O2 Flawless | 前纪 O2 无暇 | meso_O2_flawless |
| 1877 | Meso O2 Radiant | 前纪 O2 光辉 | meso_O2_radiant |
| 1878 | Meso T2 Intact | 前纪 T2 完整 | meso_T2_intact |
| 1879 | Meso T2 Exceptional | 前纪 T2 优良 | meso_T2_exceptional |
| 1880 | Meso T2 Flawless | 前纪 T2 无暇 | meso_T2_flawless |
| 1881 | Meso T2 Radiant | 前纪 T2 光辉 | meso_T2_radiant |
| 1882 | Meso T1 Intact | 前纪 T1 完整 | meso_T1_intact |
| 1883 | Meso T1 Exceptional | 前纪 T1 优良 | meso_T1_exceptional |
| 1884 | Meso T1 Flawless | 前纪 T1 无暇 | meso_T1_flawless |
| 1885 | Meso T1 Radiant | 前纪 T1 光辉 | meso_T1_radiant |
| 1886 | Lith Z1 Intact | 古纪 Z1 完整 | lith_Z1_intact |
| 1887 | Lith Z1 Exceptional | 古纪 Z1 优良 | lith_Z1_exceptional |
| 1888 | Lith Z1 Flawless | 古纪 Z1 无暇 | lith_Z1_flawless |
| 1889 | Lith Z1 Radiant | 古纪 Z1 光辉 | lith_Z1_radiant |
| 1890 | Lith H2 Intact | 古纪 H2 完整 | lith_H2_intact |
| 1891 | Lith H2 Exceptional | 古纪 H2 优良 | lith_H2_exceptional |
| 1892 | Lith H2 Flawless | 古纪 H2 无暇 | lith_H2_flawless |
| 1893 | Lith H2 Radiant | 古纪 H2 光辉 | lith_H2_radiant |
| 2013 | Prisma Twin Gremlins Weapon | 棱晶 双子小精灵 | prisma_twin_gremlins_weapon |
| 2246 | Arch-Gun Ace | Arch-枪械行家 | arch-gun_ace |
| 2248 | Arcane Scorpion Ash Helmet | ASH 毒蝎秘奥头盔 | scorpion_ash_helmet |
| 2249 | Arcane Locust Ash Helmet | ASH 飞蝗秘奥头盔 | locust_ash_helmet |
| 2250 | Arcane Reverb Banshee Helmet | BANSHEE 返响秘奥头盔 | reverb_banshee_helmet |
| 2251 | Arcane Chorus Banshee Helmet | BANSHEE 合音秘奥头盔 | chorus_banshee_helmet |
| 2252 | Arcane Phoenix Ember Helmet | EMBER 凤凰秘奥头盔 | phoenix_ember_helmet |
| 2253 | Arcane Backdraft Ember Helmet | EMBER 复燃秘奥头盔 | backdraft_ember_helmet |
| 2254 | Arcane Avalon Excalibur Helmet | EXCALIBUR 阿瓦隆秘奥头盔 | avalon_excalibur_helmet |
| 2255 | Arcane Pendragon Excalibur Helmet | EXCALIBUR 潘德拉冈秘奥头盔 | pendragon_excalibur_helmet |
| 2256 | Arcane Aurora Frost Helmet | FROST 极光秘奥头盔 | aurora_frost_helmet |
| 2257 | Arcane Squall Frost Helmet | FROST 飑风秘奥头盔 | squall_frost_helmet |
| 2258 | Arcane Essence Loki Helmet | LOKI 本质秘奥头盔 | essence_loki_helmet |
| 2259 | Arcane Swindle Loki Helmet | LOKI 诈欺秘奥头盔 | swindle_loki_helmet |
| 2260 | Arcane Coil Mag Helmet | MAG 线圈秘奥头盔 | coil_mag_helmet |
| 2261 | Arcane Gauss Mag Helmet | MAG 高斯秘奥头盔 | gauss_mag_helmet |
| 2262 | Arcane Flux Nova Helmet | NOVA 通量秘奥头盔 | flux_nova_helmet |
| 2263 | Arcane Menticide Nyx Helmet | NYX 灭神秘奥头盔 | menticide_nyx_helmet |
| 2264 | Arcane Vespa Nyx Helmet | NYX 黄蜂秘奥头盔 | vespa_nyx_helmet |
| 2265 | Arcane Thrak Rhino Helmet | RHINO 震击秘奥头盔 | thrak_rhino_helmet |
| 2266 | Arcane Vanguard Rhino Helmet | RHINO 先锋秘奥头盔 | vanguard_rhino_helmet |
| 2267 | Arcane Hemlock Saryn Helmet | SARYN 铁杉秘奥头盔 | hemlock_saryn_helmet |
| 2268 | Arcane Chlora Saryn Helmet | SARYN 氯毒秘奥头盔 | chlora_saryn_helmet |
| 2269 | Arcane Aura Trinity Helmet | TRINITY 预言秘奥头盔 | aura_trinity_helmet |
| 2270 | Arcane Meridian Trinity Helmet | TRINITY 经络秘奥头盔 | meridian_trinity_helmet |
| 2271 | Arcane Gambit Vauban Helmet | VAUBAN 策略秘奥头盔 | gambit_vauban_helmet |
| 2272 | Arcane Storm Volt Helmet | VOLT 风暴秘奥头盔 | storm_volt_helmet |
| 2273 | Arcane Pulse Volt Helmet | VOLT 脉冲秘奥头盔 | pulse_volt_helmet |
| 2321 | Prefect Balance | 完美平衡 | prefect_balance |
| 2382 | Travocyte Alloy | 铁镍合金 | travocyte_alloy |
| 2384 | Axidrol Alloy | 酸化合金 | axidrol_alloy |
| 2386 | Venerdo Alloy | 启明合金 | venerdo_alloy |
| 2388 | Hespazym Alloy | 长庚合金 | hespazym_alloy |
| 2392 | Link Shield | 护盾连结 | link_shield |

**Comment by Richasy** [comment]
感谢指正

**Comment by Cyl18** [comment]
这个物品依然无法请求成功
| 2388 | Hespazym Alloy | 长庚合金 | hespazym_alloy |
