### ISSUE TITLE
英文问题

### ISSUE THREAD

**Issue by pa001024** [Richasy/WFA_Lexicon#3]
```
蝰蛇 亡魂 -> Viper Wraith
苦痛 德特昂 -> Mara Detron
哈库纳亡魂斗篷 -> Harkonar Wraith Cloak
```

其他的我也没仔细看 可能不止这些错误
还有既然上传 麻烦请导出之后格式化一下 只有一行没有diff也不方便看

留个QQ聊一下

**Comment by Richasy** [comment]
最近提交的更新中已经对json进行了格式化。
另外就是文本名称的问题。基本是按照游戏名称来的，有些做前缀有些做后缀，这个我也没办法。

QQ：`948877853`
