### ISSUE TITLE
WF_Dict.json 内有重复的字段

### ISSUE THREAD

**Issue by vgsrerewt** [Richasy/WFA_Lexicon#4]
id 1159 - 1161 “弗拉克斯亡魂 ”
  {
    "id": 1159,
    "type": "Part",
    "zh": "弗拉克斯亡魂 蓝图",
    "en": "Furax Wraith Blueprint"
  },
  {
    "id": 1160,
    "type": "Part",
    "zh": "弗拉克斯亡魂 左拳套",
    "en": "Furax Wraith Left Gauntlet"
  },
  {
    "id": 1161,
    "type": "Part",
    "zh": "弗拉克斯亡魂 右拳套",
    "en": "Furax Wraith Right Gauntlet"
  },

与 2229-2230 ”弗拉克斯 亡魂"重复 具体数据如下

  {
    "id": 2229,
    "type": "Part",
    "zh": "弗拉克斯 亡魂 拳套",
    "en": "Furax Wraith Gauntlet"
  },
  {
    "id": 2230,
    "type": "Part",
    "zh": "弗拉克斯 亡魂 蓝图",
    "en": "Furax Wraith BP"
  },

**Comment by vgsrerewt** [comment]
id = 2212 的TITANIA也与id = 1586 的TITANIA重复

**Comment by Richasy** [comment]
**关于拳套：**

词典在最初构建时，并非严格按照游戏内的中英对照来的，而是面向如[API接口](https://ws.warframestat.us/pc)中的数据进行对照翻译的。接口中存在着简写、单词顺序错位等问题，虽然很少，但我依然将之包括进了词典之中。你目前所看到的情况正是如此，也许中文名相同，但是英文不一样。还有左拳套、右拳套和拳套是有区别的，并非重复。

---

**关于TITANIA：**

目前已修正，将其中一条改为蝶甲。

---

感谢你的指正，我就先关掉Issue啦
